// Generated by CoffeeScript 1.11.1

/*
adapted from https://www.npmjs.com/package/timestamp
 */

(function() {
  var LAST, _count, _last;

  _last = 0;

  _count = 1;

  LAST = void 0;

  module.exports = function() {
    var _t, t;
    t = Date.now();
    _t = t;
    if (_last === t) {
      _t += _count++ / 1000;
    } else {
      _count = 1;
    }
    _last = t;
    if (_t === LAST) {
      throw new Error('LAST:' + LAST + ',' + _t);
    }
    LAST = _t;
    return _t;
  };

}).call(this);

//# sourceMappingURL=monotimestamp.js.map
