// Generated by CoffeeScript 1.11.1
(function() {
  var CND, FS, LTSORT, PATH, TC, badge, debug, echo, help, include, info, log, rpr, step, templates_home, test, test_data_home, test_timer_resolution, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'TOPOCACHE/TESTS';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  test = require('guy-test');

  TC = require('./main');

  LTSORT = require('ltsort');

  PATH = require('path');

  FS = require('fs');

  step = require('coffeenode-suspend').step;

  test_data_home = PATH.resolve(__dirname, '../test-data');

  templates_home = PATH.resolve(test_data_home, 'templates');

  this._prune = function() {
    var name, ref, value;
    ref = this;
    for (name in ref) {
      value = ref[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  this._procure_test_files = function() {
    var byte_count, file_count, filename, i, len, ref, source_path, target_path;
    file_count = 0;
    ref = FS.readdirSync(templates_home);
    for (i = 0, len = ref.length; i < len; i++) {
      filename = ref[i];
      file_count += +1;
      source_path = PATH.resolve(templates_home, filename);
      target_path = PATH.resolve(test_data_home, filename);
      byte_count = this._copy_file_sync(source_path, target_path);
    }
    return whisper("copied " + file_count + " files");
  };

  this._copy_file_sync = function(source_path, target_path) {
    var source;
    FS.writeFileSync(target_path, source = FS.readFileSync(source_path));
    return source.length;
  };

  this._delay = function(handler) {
    return setTimeout(handler, 10);
  };

  this._get_source = function(path) {
    return FS.readFileSync(path, {
      encoding: 'utf-8'
    });
  };

  this._require_file = function(path) {

    /* Inhibit caching: */
    delete require['cache'][path];
    return require(path);
  };

  this._main = function() {
    return test(this, {
      'timeout': 5000
    });
  };

  this["create cache object"] = function(T, done) {
    var g, home;
    home = PATH.resolve(__dirname, '..');
    g = TC.new_cache({
      home: home
    });
    return done();
  };

  this["register file objects"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var boxed_chart, g, home;
        _this._procure_test_files();
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', 'shell::coffee -c test-data');
        boxed_chart = TC.get_boxed_chart(g);
        urge('55444', boxed_chart);
        urge('55444', '\n' + rpr((yield TC.fetch_boxed_trend(g, resume))));
        warn((yield TC.find_first_fault(g, resume)));
        urge((yield TC.find_faults(g, resume)));
        return done();
      };
    })(this));
    return null;
  };

  this["register file objects with complex keys"] = function(T, done) {
    var g, home;
    this._procure_test_files();
    home = PATH.resolve(__dirname, '../test-data');
    g = TC.new_cache({
      home: home
    });
    T.throws("expected a text, got a list", function() {
      return TC.register_fix(g, ['file', 'f.coffee'], ['file', 'f.js'], ['shell', 'coffee -c test-data']);
    });
    urge('55444', g);
    done();
    return null;
  };

  this["find fault(s) (1)"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var boxed_chart, boxed_trend, faults, first_fault, g, home;
        _this._procure_test_files();
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', 'shell::coffee -c .');
        boxed_chart = TC.get_boxed_chart(g);
        boxed_trend = (yield TC.fetch_boxed_trend(g, resume));
        first_fault = (yield TC.find_first_fault(g, resume));
        faults = (yield TC.find_faults(g, resume));
        urge(JSON.stringify(boxed_chart));
        urge(JSON.stringify(boxed_trend));
        urge(JSON.stringify(first_fault));
        urge(JSON.stringify(faults));
        return done();
      };
    })(this));
    return null;
  };

  this["find fault(s) (non-existent file)"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var error, g, home;
        _this._procure_test_files();
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        TC.register_fix(g, 'file::f.coffee', 'file::no-such-file.js', 'shell::coffee -c test-data');
        try {
          yield TC.fetch_boxed_trend(g, resume);
        } catch (error1) {
          error = error1;
          debug(JSON.stringify(error['message']));
          T.eq(error['message'], "expected a number for timestamp of 'file::no-such-file.js', got null");
        }
        return done();
      };
    })(this));
    return null;
  };

  this["find single fault"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var fault_2, fault_3, fix, fix_1, fix_2, g, home, output;
        _this._procure_test_files();
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        fix_1 = 'shell::coffee -c .';
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', fix_1);
        fault_2 = (yield TC.find_first_fault(g, resume));
        if (fault_2 != null) {
          fix_2 = fault_2['fix'];
        } else {
          fix_2 = void 0;
        }
        T.eq(fix_1, fix_2);
        if (fix_2 === fix_1) {
          fix = fix_2.replace(/^shell::\s*/, '');
          output = (yield TC.HELPERS.shell(g, fix, resume));
          T.eq(output, '');
          fault_3 = (yield TC.find_first_fault(g, resume));
          T.eq(fault_3, null);
        } else {
          T.fail("expected " + (rpr(fix_1)) + ", got " + (rpr(fix_2)));
        }
        return done();
      };
    })(this));
    return null;
  };

  this["find multiple faults"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var boxed_trend, fault, faults, fix_1, fix_2, g, home, i, j, k, len, len1, len2;
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        _this._procure_test_files();
        fix_1 = 'shell::coffee -c f.coffee';
        fix_2 = 'shell::coffee -c g.coffee';
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', fix_1);
        TC.register_fix(g, 'file::g.coffee', 'file::g.js', fix_2);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        urge('44300-1', boxed_trend = (yield TC.fetch_boxed_trend(g, resume)));
        T.eq(boxed_trend, [['file::f.coffee'], ['file::g.coffee'], ['file::f.js'], ['file::g.js']]);
        T.eq((yield TC.find_faults(g, resume)), []);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        urge('44300-2', boxed_trend = (yield TC.fetch_boxed_trend(g, resume)));
        T.eq(boxed_trend, [['file::g.coffee'], ['file::g.js'], ['file::f.js'], ['file::f.coffee']]);
        faults = (yield TC.find_faults(g, resume));
        T.eq(faults, [
          {
            "effect": "file::f.js",
            "cause": "file::f.coffee",
            "fix": "shell::coffee -c f.coffee"
          }
        ]);
        for (i = 0, len = faults.length; i < len; i++) {
          fault = faults[i];
          help(JSON.stringify(fault));
        }
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        urge('44300-3', boxed_trend = (yield TC.fetch_boxed_trend(g, resume)));
        T.eq(boxed_trend, [['file::g.js'], ['file::f.js'], ['file::f.coffee'], ['file::g.coffee']]);
        faults = (yield TC.find_faults(g, resume));
        T.eq(faults, [
          {
            "cause": "file::f.coffee",
            "effect": "file::f.js",
            "fix": "shell::coffee -c f.coffee"
          }, {
            "cause": "file::g.coffee",
            "effect": "file::g.js",
            "fix": "shell::coffee -c g.coffee"
          }
        ]);
        for (j = 0, len1 = faults.length; j < len1; j++) {
          fault = faults[j];
          help(JSON.stringify(fault));
        }
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        urge('44300-4', boxed_trend = (yield TC.fetch_boxed_trend(g, resume)));
        T.eq(boxed_trend, [['file::g.js'], ['file::f.js'], ['file::g.coffee'], ['file::f.coffee']]);
        for (k = 0, len2 = faults.length; k < len2; k++) {
          fault = faults[k];
          help(JSON.stringify(fault));
        }
        return done();
      };
    })(this));
    return null;
  };

  this["align multiple faults (1)"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var boxed_trend, command, fault, faults, first_fault, fix, fix_1, fix_2, fix_count, g, home, i, j, len, len1, output, protocol, ref;
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        _this._procure_test_files();
        fix_1 = 'shell::coffee -c f.coffee';
        fix_2 = 'shell::coffee -c g.coffee';
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', fix_1);
        TC.register_fix(g, 'file::g.coffee', 'file::g.js', fix_2);
        TC.register_fix(g, 'file::g.js', 'file::f.js', fix_1);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        urge('44300', boxed_trend = (yield TC.fetch_boxed_trend(g, resume)));
        T.eq(boxed_trend, [['file::f.coffee'], ['file::g.coffee'], ['file::f.js'], ['file::g.js']]);
        faults = (yield TC.find_faults(g, resume));
        debug('22122', JSON.stringify(faults));
        T.eq(faults, [
          {
            "cause": "file::g.js",
            "effect": "file::f.js",
            "fix": "shell::coffee -c f.coffee"
          }
        ]);
        for (i = 0, len = faults.length; i < len; i++) {
          fault = faults[i];
          help(JSON.stringify(fault));
        }
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        urge('44300', boxed_trend = (yield TC.fetch_boxed_trend(g, resume)));
        faults = (yield TC.find_faults(g, resume));
        debug('22122', JSON.stringify(faults));
        T.eq(faults, [
          {
            "cause": "file::g.coffee",
            "effect": "file::g.js",
            "fix": "shell::coffee -c g.coffee"
          }, {
            "cause": "file::f.coffee",
            "effect": "file::f.js",
            "fix": "shell::coffee -c f.coffee"
          }, {
            "cause": "file::g.js",
            "effect": "file::f.js",
            "fix": "shell::coffee -c f.coffee"
          }
        ]);
        first_fault = (yield TC.find_first_fault(g, resume));
        T.eq(first_fault, faults[0]);
        for (j = 0, len1 = faults.length; j < len1; j++) {
          fault = faults[j];
          help(JSON.stringify(fault));
        }
        fix_count = 0;
        while ((fault = (yield TC.find_first_fault(g, resume))) != null) {
          urge(fault);
          fix_count += +1;
          if (fix_count > 10) {
            T.fail("runaway loop?");
            break;
          }
          fix = fault.fix;
          ref = TC.split_key(g, fix), protocol = ref[0], command = ref[1];
          if (protocol === 'shell') {
            output = (yield TC.HELPERS.shell(g, command, resume));
            T.eq(output, '');
          } else {
            T.fail("expected protocol to be 'shell', got " + (rpr(protocol)) + " from key " + (rpr(fail)));
          }
          help((yield TC.HELPERS.shell(g, "ls -l -tr ./", resume)));
        }
        T.eq(fix_count, 2);
        info(TC.get_boxed_chart(g));
        help(g);
        return done();
      };
    })(this));
    return null;
  };

  this["align multiple faults (2)"] = function(T, done) {
    step((function(_this) {
      return function*(resume) {
        var fault, g, home, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, report;
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        _this._procure_test_files();
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', ['shell', ['coffee', '-c', 'f.coffee']]);
        TC.register_fix(g, 'file::g.coffee', 'file::g.js', ['shell', 'coffee -c g.coffee']);
        TC.register_fix(g, 'file::g.js', 'file::f.js', ['shell', ['coffee', '-c', 'f.coffee']]);
        yield TC.HELPERS.touch(g, 'file::f.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.js', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::g.coffee', resume);
        yield _this._delay(resume);
        yield TC.HELPERS.touch(g, 'file::f.coffee', resume);
        yield _this._delay(resume);
        fault = (yield TC.find_first_fault(g, resume));
        T.eq(fault, {
          "cause": "file::g.coffee",
          "effect": "file::g.js",
          "fix": ["shell", "coffee -c g.coffee"]
        });
        report = (yield TC.align(g, resume));
        info(report);
        T.eq((ref = report['runs']) != null ? ref.length : void 0, 2);
        T.eq((ref1 = report['runs']) != null ? (ref2 = ref1[0]) != null ? ref2['cause'] : void 0 : void 0, 'file::g.coffee');
        T.eq((ref3 = report['runs']) != null ? (ref4 = ref3[1]) != null ? ref4['cause'] : void 0 : void 0, 'file::f.coffee');
        T.eq((ref5 = report['runs']) != null ? (ref6 = ref5[0]) != null ? ref6['kind'] : void 0 : void 0, 'shell');
        T.eq((ref7 = report['runs']) != null ? (ref8 = ref7[1]) != null ? ref8['kind'] : void 0 : void 0, 'shell');
        help((yield TC.HELPERS.shell(g, "ls -l -tr ./", resume)));
        return done();
      };
    })(this));
    return null;
  };

  this["fixes can be strings, lists"] = function(T, done) {
    step((function(_this) {
      return function(resume) {
        var fix, fixes, g, home, i, len;
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', ['shell', ['coffee', '-c', 'f.coffee']]);
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', ['shell', 'coffee -c g.coffee']);
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', 'shell::coffee -c g.coffee');
        fixes = [['shell', ['coffee', '-c', 'f.coffee']], ['shell', 'coffee -c g.coffee'], 'shell::coffee -c g.coffee'];
        for (i = 0, len = fixes.length; i < len; i++) {
          fix = fixes[i];
          urge(CND.orange(rpr(fix)), CND.steel(rpr("json::" + (JSON.stringify(fix)))));
        }
        return done();
      };
    })(this));
    return null;
  };

  this["toytrain demo"] = require('./toytrain-demo');

  this["catalog"] = function(T, done) {
    return step((function(_this) {
      return function(resume) {
        var g, home;
        home = PATH.resolve(__dirname, '../test-data');
        g = TC.new_cache({
          home: home
        });
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', ['shell', ['coffee', '-c', 'f.coffee']]);
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', ['shell', 'coffee -c g.coffee']);
        TC.register_fix(g, 'file::f.coffee', 'file::f.js', 'shell::coffee -c g.coffee');
        debug(TC.get_ids(g));
        debug(TC.get_file_ids(g));
        debug(TC.get_file_paths(g));
        return done();
      };
    })(this));
  };

  this["toposort of fixes"] = function(T, done) {
    throw new Error("test not ready");
    step((function(_this) {
      return function(resume) {
        var _, cause, effect, fix, fix_1, fix_2, fix_txt, fxg, g, ref, relation;
        g = TC.new_cache({
          home: PATH.resolve(__dirname, '../test-data')
        });
        fix_1 = ['shell', 'coffee -c f.coffee'];
        fix_2 = ['shell', 'coffee -c g.coffee'];
        TC.register_fix(g, 'f.coffee', 'file::f.js', fix_1);
        TC.register_fix(g, 'file::g.coffee', 'file::g.js', fix_2);
        TC.register_fix(g, 'file::g.js', 'file::f.js', fix_1);
        info(TC.get_boxed_chart(g));
        fxg = TC.new_cache();
        ref = g['fixes'];
        for (_ in ref) {
          relation = ref[_];
          cause = relation.cause, effect = relation.effect, fix = relation.fix;
          whisper((rpr(cause)) + " >—— " + (rpr(fix)) + " ——> " + (rpr(effect)));
          fix_txt = CND.isa_text(fix) ? fix : JSON.stringify(fix);
          TC.register_fix(fxg, cause, fix_txt);
          TC.register_fix(fxg, fix_txt, effect);
        }
        urge(TC.get_boxed_chart(fxg));
        return done();
      };
    })(this));
    return null;
  };

  if (module.parent == null) {
    include = ["catalog"];
    this._prune();
    this._main();
    test_timer_resolution = function() {
      return step(function*(resume) {
        var d1, d2, g, now, now1, t0, t1, t_f, t_g;
        g = TC.new_cache();
        now1 = Date.now;
        now = require('./monotimestamp');
        d1 = [now1(), now1(), now1(), now1(), now1(), now1(), now1()];
        d2 = [now(), now(), now(), now(), now(), now(), now()];
        help(d1);
        help(d2);
        t0 = now();
        yield TC.HELPERS.touch(g, 'file::test-data/f.coffee', resume);
        yield TC.HELPERS.touch(g, 'file::test-data/g.coffee', resume);
        t1 = now();
        t_f = ((yield FS.stat('test-data/f.coffee', resume))).mtime.getTime();
        t_g = ((yield FS.stat('test-data/g.coffee', resume))).mtime.getTime();
        urge(t0);
        help(t_f);
        help(t_g);
        urge(t1);
        return info(CND.truth(((t0 < t_f && t_f < t_g) && t_g < t1)));
      });
    };
  }


  /*
    step ( resume ) ->
       * stamper = ( me, id, handler ) ->
       *   debug rpr id
       *   process.exit()
      #.......................................................................................................
      f = ->
        if ( R = TC.get graph, 'result of f()' )?
          whisper "result of f(): from cache"
          return R
        whisper "result of f(): computed"
        return TC.set graph, 'result of f()', 42 * 2
  
      #.......................................................................................................
       * stamper = TC.HELPERS.cache_stamper
       * graph   = TC.new_cache { stamper, }
      graph   = TC.new_cache()
      TC.register_fix graph, [ 'cache', 'definition of f', ], [ 'cache', 'result of f()', ], [ 'call', ( => TC.delete graph, 'result of f()' ), ]
      TC.register_change graph, 'definition of f'
      #.......................................................................................................
      debug 'trend:', yield TC.fetch_boxed_trend  graph, resume
      help  'faults:', yield TC.find_faults        graph, resume
      #.......................................................................................................
      urge graph[ 'store' ]
      urge graph[ 'store' ]
      #.......................................................................................................
      debug 'trend:', yield TC.fetch_boxed_trend  graph, resume
      help  'faults:', yield TC.find_faults        graph, resume
      #.......................................................................................................
      debug f()
      debug f()
      #.......................................................................................................
      debug 'trend:', yield TC.fetch_boxed_trend  graph, resume
      help  'faults:', yield TC.find_faults        graph, resume
      #.......................................................................................................
      TC.register_change graph, 'definition of f'
      #.......................................................................................................
      debug 'trend:', yield TC.fetch_boxed_trend  graph, resume
      help  'faults:', yield TC.find_faults        graph, resume
      #.......................................................................................................
      info yield TC.align graph, resume
      urge graph[ 'store' ]
      #.......................................................................................................
      debug f()
      debug f()
      #.......................................................................................................
      urge graph[ 'store' ]
   */

}).call(this);

//# sourceMappingURL=tests.js.map
